ekf_filter_node:
  ros__parameters:
    frequency: 30.0
    sensor_timeout: 0.2
    two_d_mode: true
    publish_tf: true

    map_frame: map
    odom_frame: odom
    base_link_frame: base_footprint
    world_frame: odom

    # Odometry (wheel encoders)
    odom0: /odom
    odom0_config:
          [ true,  true,  false,    # x, y, z
            false, false, false,    # roll, pitch, yaw
            false,  false,  false,    # vx, vy, vz
            false, false, false,    # vroll, vpitch, vyaw
            false, false, false ]   # ax, ay, az



    # IMU (gyro for yaw rate, accelerometer)
    imu0: /imu/data
        imu0_differential: false
        imu0_relative: false
    imu0_config:
          [ false, false, false,  # x, y, z
            false, false, true,   # roll, pitch, yaw
            false, false, false,   # vx, vy, vz
          false, false, false,   # vroll, vpitch, vyaw
            false, false, false ]  # ax, ay, az


    # odom0_pose_covariance:  [0.1,  0.0,  0.0,  0.0, 0.0, 0.0,
    #                          0.0,  0.1,  0.0,  0.0, 0.0, 0.0,
    #                          0.0,  0.0,  1e6,  0.0, 0.0, 0.0,
    #                          0.0,  0.0,  0.0,  1e6, 0.0, 0.0,
    #                          0.0,  0.0,  0.0,  0.0, 1e6, 0.0,
    #                          0.0,  0.0,  0.0,  0.0, 0.0, 0.1]

    # odom0_twist_covariance: [0.05, 0.0, 0.0, 0.0, 0.0, 0.0,
    #                          0.0, 0.05, 0.0, 0.0, 0.0, 0.0,
    #                          0.0, 0.0, 1e6, 0.0, 0.0, 0.0,
    #                          0.0, 0.0, 0.0, 1e6, 0.0, 0.0,
    #                          0.0, 0.0, 0.0, 0.0, 1e6, 0.0,
    #                          0.0, 0.0, 0.0, 0.0, 0.0, 0.1]
    # imu0_pose_covariance:  [1e6, 0.0, 0.0, 0.0, 0.0, 0.0,
    #                         0.0, 1e6, 0.0, 0.0, 0.0, 0.0,
    #                         0.0, 0.0, 1e6, 0.0, 0.0, 0.0,
    #                         0.0, 0.0, 0.0, 1e6, 0.0, 0.0,
    #                         0.0, 0.0, 0.0, 0.0, 1e6, 0.0,
    #                         0.0, 0.0, 0.0, 0.0, 0.0, 0.01]

    # imu0_twist_covariance: [1e6, 0.0, 0.0, 0.0, 0.0, 0.0,
    #                         0.0, 1e6, 0.0, 0.0, 0.0, 0.0,
    #                         0.0, 0.0, 1e6, 0.0, 0.0, 0.0,
    #                         0.0, 0.0, 0.0, 1e6, 0.0, 0.0,
    #                         0.0, 0.0, 0.0, 0.0, 1e6, 0.0,
    #                         0.0, 0.0, 0.0, 0.0, 0.0, 0.02]

    # # Process noise covariance
    # process_noise_covariance: [0.05, 0.0,   0.0,   0.0,   0.0,   0.0,
    #                            0.0,  0.05,  0.0,   0.0,   0.0,   0.0,
    #                            0.0,  0.0,   1e6,   0.0,   0.0,   0.0,
    #                            0.0,  0.0,   0.0,   1e6,   0.0,   0.0,
    #                            0.0,  0.0,   0.0,   0.0,   1e6,   0.0,
    #                            0.0,  0.0,   0.0,   0.0,   0.0,   0.05]

    # # Initial covariance
    # initial_state: [0.0, 0.0, 0.0, 0.0, 0.0, 0.0]

    # initial_estimate_covariance: [1e-9, 0.0,   0.0,   0.0,   0.0,   0.0,
    #                               0.0,  1e-9,  0.0,   0.0,   0.0,   0.0,
    #                               0.0,  0.0,   1e-9,  0.0,   0.0,   0.0,
    #                               0.0,  0.0,   0.0,   1e-9,  0.0,   0.0,
    #                               0.0,  0.0,   0.0,   0.0,   1e-9,  0.0,
    #                               0.0,  0.0,   0.0,   0.0,   0.0,   1e-9]
